FizzBuzzMVC/Models/ErrorViewModel.cs
using System;

namespace FizzBuzzMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FizzBuzzMVC/Models/FizzBuzzModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace FizzBuzzMVC.Models
{
    public class FizzBuzzModel
    {
        public int FirstNumber { get; set; }
        public int LastNumber { get; set; }

        public List<string> Results { get; set; } = new List<string>();

    }
}

FizzBuzzMVC/Controllers/FizzbuzzController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FizzBuzzMVC.Models;

namespace FizzBuzzMVC.Controllers
{
    public class FizzbuzzController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            FizzBuzzModel model = new();

            model.FirstNumber = 4;
            model.LastNumber = 7;

            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(FizzBuzzModel model)
        {
            List<string> results = new List<string>();

            

            for(int i = 1; i <= 100; i++)
            {
                if(i%model.FirstNumber==0 && i%model.LastNumber== 0)
                {
                    //divisible by both fizz and buzz
                    results.Add("FizzBuzz");
                }
                else if(i%model.FirstNumber == 0)
                {
                    //divisible by only Fizz number only
                    results.Add("Fizz");
                }
                else if(i%model.LastNumber == 0)
                {
                    //divisible by only buzz only
                    results.Add("Buzz");
                }
                else
                {
                    //not divisible by either fizz or buzz
                    results.Add(i.ToString());
                }
            }

            model.Results = results;

            //Console.WriteLine(model.Results);
            
            return View(model);
        }




    }
}

FizzBuzzMVC/Controllers/HomeController.cs
using FizzBuzzMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FizzBuzzMVC.Controllers
{
    public class HomeController : Controller
    {
        /*private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }**/

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
         



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FizzBuzzMVC/Views/Fizzbuzz/Index.cshtml
@model FizzBuzzMVC.Models.FizzBuzzModel


<div class="container">
    <div class="row row-cols-1 row-cols-md-2">
        <div class="col col-md-4">
            <h2>Fizz Buzz: A javascript coding project</h2>
            <h5 class="lead">
                When it counts you Fizz Buzz. A Javascript coding exercise using loops.
                This program prints the numbers from 1 to 100 and for multiples of a Fizz Values displays
                'Fizz' instead of the number and for the multiples of a Buzz displays 'Buzz'. If it is a  multiple
                of both, displays "FizzBuzz".
            </h5>
            <h2 class="border-bottom border-1" style="margin-top:50px">Instructions</h2>
            <h5 class="lead">
                Enter the Fizz (first input) and Buzz (second input) values, then press the button to see the values appear.
            </h5>
        </div>
        <div class="col col-md-8">
            <div>
                <h5>Enter Values</h5>

                <form class="row gy-2" asp-action="Index" asp-controller="Fizzbuzz" method="post">
                    <div class="col">
                        <input asp-for="FirstNumber" name="FirstNumber" type="Number" id="startValueInput" class="form-control"
                               value="@Model.FirstNumber" min="1">
                    </div>

                    <div class="col">
                        <input asp-for="LastNumber" name="LastNumber" type="Number" id="endValueInput" class="form-control"
                               value="@Model.LastNumber" max="100">
                    </div>

                    <div class="col-12 d-flex">
                        <button type="submit" id='btnSubmit' class="btn btn-dark btn-lg">
                            Fizz The Buzz
                        </button>
                    </div>

                </form>

                <h2 class="border-bottom border-1">Results</h2>
                <div class="table-responsive">
                    

                    <table class="table table-striped table-hover table-dark table-sm">
                        <thead>
                            <tr>
                                <td colspan="5">FizzBuzz Results</td>
                            </tr>
                        </thead>

                        @if (@Model.Results.Count() > 0)
                        {


                            @for (int i = 0; i < @Model.Results.Count(); i += 5)
                            {
                                <tr>

                                    <td>@Model.Results[i] </td>


                                    @if (i + 1 < Model.Results.Count())
                                    {
                                        <td>@Model.Results[i + 1]</td>

                                    }

                                    @if (i + 2 < Model.Results.Count())
                                    {
                                        <td>@Model.Results[i + 2]</td>

                                    }

                                    @if (i + 3 < Model.Results.Count())
                                    {
                                        <td>@Model.Results[i + 3]</td>

                                    }

                                    @if (i + 4 < Model.Results.Count())
                                    {
                                        <td>@Model.Results[i + 4]</td>

                                    }

                                </tr>
                            }


                        }

                    </table>
                </div>
            </div>

        </div>
    </div>

</div>

FizzBuzzMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}




<!--- =================== main Section ====================-->
<main class="flex-shrink-0">
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row g-5  py-5 row-cols-1 row-cols-lg-2">
            <div class="col order-last order-lg-first">
                <h1 class="display-5 fw-bold lh-1 mb-3">Fizz Buzz: A Coding Project</h1>
                <h4 class="lead">
                    When it counts you Fizz Buzz. A Javascript coding exercise using loops.
                    This is a program that prints the numbers from 1 to 100 and for multiples of Fizz values (chosen by the user), it displays
                    'Fizz' instead of the number.For the multiples of Buzz values (chosen by the user), it displays 'Buzz'. For multiples of
                    both Fizz and Fuzz, it displays 'FizzBuzz'. ALl other values are displayed as usual.
                </h4>
                <ul class="fa-ul pt-2 checklist">
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>CSS and Bootstrap Layout</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript Fundamentals</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript Loops</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript Functions</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript DOM Manipulation</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript If/Then/Else</li>
                    <li><span class="fa-li"><i class="fas fa-check-square"></i></span>Javascript Boolean Logic</li>
                </ul>
                <div>
                    <a type="button" class="btn btn-outline-dark btn-lg px-4 me-md-2" href="app.html">Try It Out</a>
                </div>

                <div class="fw-bold mt-5">
                    <div class="d-flex">
                        <div class="row">
                            <div class="col"><h1>C#</h1></div>
                            <div class="col"><i class="fab fa-bootstrap fa-3x bsicon"></i></div>
                            <div class="col"><i class="fab fa-html5 fa-3x html5icon"></i></div>
                            <div class="col"><i class="fab fa-css3-alt fa-3x css3icon"></i></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <img src="img/fizzBuzzImage2.svg" alt="logo for Fizz Buzz project"
                     class="img-fluid center-block d-block mx-auto" width="500"/>
            </div>
        </div>
    </div>
</main>
<!--- =================== End of main Section ====================-->

FizzBuzzMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FizzBuzzMVC</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/5db21ba9c6.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="height:8vh">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FizzBuzzMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fizzbuzz" asp-action="Index">The App</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main id="content" class="flex-shrink-0" style="min-height:85vh">
        @RenderBody()
    </main>


    <!--- =================== footer Section ====================-->
    <div class="bg-dark" style="height:7vh">
        <div class="container-fluid text-center">
            <div class="row row-cols-1 row-cols-md-3 gy-2">
                <div class="col text-light order-last order-md-first">
                    <div><span class="text-muted">&copy;2021</span> Dr. John Teye Brown | teyeologo@gmail.com</div>
                </div>
                <div class="col d-flex align-items-center justify-content-center text-muted">
                    <span>Teye Brown</span>
                </div>
                <div class="col d-flex align-items-center justify-content-center justify-content-md-end">
                    <div class="row">
                        <div class="col social"><a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-linkedin"></i></a></div>
                        <div class="col social"><a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-github "></i></a></div>
                        <div class="col social"><a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-twitter "></i></a></div>
                        <div class="col social"><a href="#" target="_blank" rel="noopener noreferrer"><i class="fab fa-google "></i></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>